# _config.yml

# required, replace with your own information -----
title: hello
author: Sara Gong
email: saragong@usc.edu 
description: > 
  A minimalist template for designing a personal Github Pages website - without typing a single line of code.

#---------------------------------------------------
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

