# _config.yml

# required, replace with your own information -----
title: Hello for Github Pages
author: Sara Gong
description: > 
  A minimalist template for designing a personal GitHub Pages website - without typing a single line of code.
baseurl: ""
url: https://saragong.github.io//hello # replace with https://*your-username*.github.io/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

